apiVersion: v1
kind: Service
metadata:
  name: aynapp-service
  namespace: aynur
spec:
  type: ClusterIP
  selector:
    aynur: diploma
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: 80
