---
- name: Подготовка всех узлов
  hosts: k8s_cluster
  become: true
  roles:
    - common

- name: Инициализация мастера
  hosts: master
  become: true
  roles:
    - master

- name: Присоединение воркеров
  hosts: workers
  become: true
  roles:
    - worker