---
- name: Проверка присоединения узля
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Присоединить воркер к кластеру
  command: "{{ hostvars[groups['master'][0]].kubeadm_join_command }}"
  when: not kubelet_conf.stat.exists